Demo1-Day2/Models/Department.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace Demo1_Day2.Models
{
    public class Department
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        
        public int DeptId { get; set; }
        [Remote("CheckDeptId","Department")]

        [Required]
        
        public string DeptName { get; set; }
        public int Capacity { get; set; }
        
        public bool Status { get; set; }
        public ICollection<Student> Students { get; set; } = new HashSet<Student>();
        public List<Course> Courses { get; set; }=new List<Course>();

    }
}

Demo1-Day2/Controllers/DepartmentController.cs
using Demo1_Day2.Controllers.CustomFilters;
using Demo1_Day2.Data;
using Demo1_Day2.Models;
using Demo1_Day2.Repos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;

namespace Demo1_Day2.Controllers
{
    public class DepartmentController : Controller
    {
        IDepartmentRepo deptRepo;
       
        public DepartmentController( IDepartmentRepo _deptrepo)
        {
            deptRepo=_deptrepo;
        }
        public IActionResult Index()
        {
            var departments= deptRepo.GetAll();
            return View(departments);
        }
        // [AuthFilter]
      
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View(new Department());
        }
        [HttpPost]
        public IActionResult Create(Department dept)
        {
            if (ModelState.IsValid)
            {
                dept.Status=true;
                deptRepo.AddDept(dept);
                return RedirectToAction("Index");
            }
            return View(dept);           
        }
       [Authorize(Roles = "Student")]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();//return 400 status code
            }
            var dept = deptRepo.GetDeptById(id);
            if (dept == null)
            {
                return NotFound();//return 404 status code
            }
            return View(dept);
        }
        //[Authorize]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var dept = deptRepo.GetDeptById(id);
            if (dept == null)
            {
                return NotFound();
            }
            return View(dept);
        }
        [HttpPost]
        public IActionResult Edit(Department dept)
        {
            if (dept.DeptId==0 || dept.DeptName==null)
            {
                return View(dept);
            }
            deptRepo.UpdateDept(dept);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var dept = deptRepo.GetDeptById(id);
            if (dept == null)
            {
                return NotFound();
            }
            deptRepo.DeleteDeptSoft(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CheckDeptId(int deptId)
        {
            var model = deptRepo.GetDeptById(deptId);
            if (model == null)
            {
                return Json(true);
            }
          //  int x = db.Departments.Max(d => d.DeptId);
            return Json(false);
        }
    }
}

Demo1-Day2/Controllers/DeptCourseController.cs
using Demo1_Day2.Data;
using Demo1_Day2.Models;
using Demo1_Day2.Repos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo1_Day2.Controllers
{
    public class DeptCourseController : Controller
    {
        //ITIContext db = new ITIContext();
        ICourseRepo crsRepo;
        IDepartmentRepo deptRepo;
        IDeptCourseRepo deptCrsRepo;
        public DeptCourseController(ICourseRepo _crsRepo, IDepartmentRepo _deptRepo, IDeptCourseRepo _deptCrsRepo)
        {
            crsRepo = _crsRepo;
            deptRepo = _deptRepo;
            deptCrsRepo = _deptCrsRepo;

        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ShowCoursesByDept(int id)
        { 
            var dept = deptRepo.GetDeptWithCoursesById(id);
            return View(dept);
        }
        [HttpGet]
        public IActionResult ManageDeptCourses(int id)
        {
            var dept = deptRepo.GetDeptWithCoursesById(id);
            var courses = dept.Courses;
            var allCourses = crsRepo.GetAll();
            var notInDept = allCourses.Except(courses).ToList();
            ViewBag.Dept = dept;
            ViewBag.NotInDept = notInDept;
            return View();
        }
        [HttpPost]
        public IActionResult ManageDeptCourses(int deptId, List<int> coursesToAdd,List<int> coursesToRemove)
        {
            
            var dept = deptRepo.GetDeptWithCoursesById(deptId);
            foreach (var item in coursesToRemove)
            {
                Course course =crsRepo.GetById(item);
                dept.Courses.Remove(course);
            }
            foreach (var item in coursesToAdd)
            {
                Course course = crsRepo.GetById(item);
                dept.Courses.Add(course);
            }
            deptCrsRepo.Saving();
            return RedirectToAction("Index", "Department");
        }

    }
}

Demo1-Day2/Views/Department/Create.cshtml
@model Department

    <div class="container bg-info text-center p-5 m-5 ">
        <form method="post">
            <label asp-for="DeptId"></label>
            <input asp-for="DeptId" /><br />
            <label asp-for="DeptName"></label>
            <input asp-for="DeptName" /><br />
            <label asp-for="Capacity"></label>
            <input asp-for="Capacity" /><br />
            <input type="submit" value="Create" class="btn btn-primary" />
            <a asp-controller="department" asp-action="Index" class="btn btn-info">Back</a>
        </form>
    </div>
    <div asp-validation-summary="All" class="alert alert-danger list-unstyled"></div>
    @section ValidationScripts{

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validationunobtrusive/jquery.validate.unobtrusive.js"></script>
    }

Demo1-Day2/Views/Department/Details.cshtml
@model Department

<div class="alert alert-warning text-center">
  <h3>
  @Model.DeptId :: @Model.DeptName :: @Model.Capacity
    </h3>
</div>

Demo1-Day2/Views/Department/Edit.cshtml
@model Department

    <div class="container bg-gradient text-center p-5 m-5 ">
        <form method="post">
            <label asp-for="DeptId"></label>
            <input asp-for="DeptId" readonly /><br />
            <label asp-for="DeptName"></label>
            <input asp-for="DeptName" /><br />
            <label asp-for="Capacity"></label>
            <input asp-for="Capacity" /><br />
            <label asp-for="Status"></label>
            <input asp-for="Status" /><br />
            <input type="submit" value="Edit" class="btn btn-primary" />
            <a asp-controller="department" asp-action="Index" class="btn btn-info">Back</a>
        </form>
    </div>

Demo1-Day2/Views/Department/Index.cshtml
@model IEnumerable<Department>



    <h1 class="text-center">Departments list</h1>
    <table class="table table-bordered table-hover m-3">
    @if (User.IsInRole("Admin"))
    { 
        <a asp-controller="Department" asp-action="Create" class="btn btn-success">Create</a>
     } 
        <thead class="text-center">
            <tr>
                <th>Dept ID</th>
                <th>Department Name</th>
                <th>Capacity</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count()==0)
            {
                <tr>
                    <td colspan="4">No Students Exists</td>
                </tr>
            }
            else
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.DeptId</td>
                        <td>@item.DeptName</td>
                        <td>@item.Capacity</td>
                        
                        <td>
                            <a asp-controller="department" asp-action="Details" asp-route-id="@item.DeptId" class="btn btn-info">Details</a>
                            <a asp-controller="department" asp-action="Edit" asp-route-id="@item.DeptId" class="btn btn-primary">Edit</a>
                            <a onclick="return confirm('Are you sure you want to delete this record?')" asp-controller="department" asp-action="Delete" asp-route-id="@item.DeptId" class="btn btn-danger">Delete</a>
                            <a asp-controller="DeptCourse" asp-action="ShowCoursesByDept" asp-route-id="@item.DeptId" class="btn btn-secondary">Courses in @item.DeptName</a>
                            <a asp-controller="DeptCourse" asp-action="ManageDeptCourses" asp-route-id="@item.DeptId" class="btn btn-warning">change Department Courses</a>
                        </td>
                    </tr>

                }
            }
        </tbody>
    </table>
    