Demo1-Day2/Controllers/CourseController.cs
using Demo1_Day2.Data;
using Demo1_Day2.Repos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo1_Day2.Controllers
{
    public class CourseController : Controller
    {
        ICourseRepo crsRepo;
        public CourseController(ICourseRepo _crsRepo)
        {
            crsRepo = _crsRepo;
        }
        public IActionResult Index()
        {
            var courses= crsRepo.GetAll();
            return View(courses);
        }
        public IActionResult Create()
        {
            return View(new Course());
        }
        [HttpPost]
        public IActionResult Create(Course course)
        {
            if(ModelState.IsValid)
            {
                bool isDuplicate = crsRepo.Duplicate(course.CrsName);
                if (isDuplicate)
                {
                    ModelState.AddModelError("CrsName", "Not Valid Course name, it already exists.");
                    return View(course);
                }
                try
                {
                    crsRepo.Add(course);
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("CrsId", "Not Valid Course Id, it already exists.");
                    return View(course);
                }

            
                return RedirectToAction("Index");
            }
                return View(course);
                    
        }
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var crs = crsRepo.GetById(id);
            if (crs == null)
            {
                return NotFound();
            }
            crsRepo.Delete(crs);
            return RedirectToAction("Index");
        }
    }
}

Demo1-Day2/Controllers/DepartmentController.cs
using Demo1_Day2.Controllers.CustomFilters;
using Demo1_Day2.Data;
using Demo1_Day2.Models;
using Demo1_Day2.Repos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;

namespace Demo1_Day2.Controllers
{
    public class DepartmentController : Controller
    {
        IDepartmentRepo deptRepo;
       
        public DepartmentController( IDepartmentRepo _deptrepo)
        {
            deptRepo=_deptrepo;
        }
        public IActionResult Index()
        {
            var departments= deptRepo.GetAll();
            return View(departments);
        }
        // [AuthFilter]
      
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View(new Department());
        }
        [HttpPost]
        public IActionResult Create(Department dept)
        {
            if (ModelState.IsValid)
            {
                dept.Status=true;
                deptRepo.AddDept(dept);
                return RedirectToAction("Index");
            }
            return View(dept);           
        }
       [Authorize(Roles = "Student")]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();//return 400 status code
            }
            var dept = deptRepo.GetDeptById(id);
            if (dept == null)
            {
                return NotFound();//return 404 status code
            }
            return View(dept);
        }
        //[Authorize]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var dept = deptRepo.GetDeptById(id);
            if (dept == null)
            {
                return NotFound();
            }
            return View(dept);
        }
        [HttpPost]
        public IActionResult Edit(Department dept)
        {
            if (dept.DeptId==0 || dept.DeptName==null)
            {
                return View(dept);
            }
            deptRepo.UpdateDept(dept);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var dept = deptRepo.GetDeptById(id);
            if (dept == null)
            {
                return NotFound();
            }
            deptRepo.DeleteDeptSoft(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CheckDeptId(int deptId)
        {
            var model = deptRepo.GetDeptById(deptId);
            if (model == null)
            {
                return Json(true);
            }
          //  int x = db.Departments.Max(d => d.DeptId);
            return Json(false);
        }
    }
}

Demo1-Day2/Controllers/StudentController.cs
using Demo1_Day2.Data;
using Demo1_Day2.Models;
using Demo1_Day2.Repos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Demo1_Day2.Controllers
{
    public class StudentController : Controller
    {
        IDepartmentRepo deptRepo;
        IStudentRepo stdRepo;
        public StudentController(IStudentRepo _studentRepo, IDepartmentRepo _deptrepo)
        {
            stdRepo = _studentRepo;
            deptRepo= _deptrepo;
        }
        public IActionResult Index()
        {
            var students = stdRepo.GetAll();

            return View(students);
        }
        public IActionResult Create()
        {
            ViewBag.Departments = deptRepo.GetAll();
            return View(new Student());
        }
        [HttpPost]
        public async Task<IActionResult> Create(Student std,IFormFile stdImg)
        {
            if (ModelState.IsValid)
            {
                var department = deptRepo.GetDeptWithStdById(std.DeptNo);
                if (department != null)
                {
                    if (department.Students.Count() >= department.Capacity)
                    {
                        ModelState.AddModelError("Capacity", $"The department can only have {department.Capacity} students.Unfortunately, this department has reached its limit, choose another one. ");
                        ViewBag.Departments = deptRepo.GetAll();
                        return View(std);
                    }
                    stdRepo.Add(std);
                    if(stdImg == null)
                    {
                        ModelState.AddModelError("StdImgName", $"Choose an image please");
                        ViewBag.Departments = deptRepo.GetAll();
                        return View(std);
                    }
                    string filename = $"{std.StudentId}.{stdImg.FileName.Split(".").Last()}";
                    using(var fs=new FileStream("wwwroot/images/"+filename, FileMode.Create))
                    {
                        await stdImg.CopyToAsync(fs);
                        std.StdImgName=filename;
                        stdRepo.UpdateStudentImage(filename, std.StudentId);
                    }
                    return RedirectToAction("Index");
                }
               
            }
            ViewBag.Departments = deptRepo.GetAll();
            return View(std);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var std = stdRepo.GetStdById(id??0);
            if (std == null)
            {
                return NotFound();
            }
            ViewBag.Departments = deptRepo.GetAll();
            return View(std);
        }
        [HttpPost]
        public IActionResult Edit(Student std)
        {
            if (std.StudentId==0 || std.StudentName==null)
            {
                return View(std);
            }
            stdRepo.UpdateStd(std);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var std = stdRepo.GetStdById(id);
            if (std == null)
            {
                return NotFound();
            }
            stdRepo.DeleteStd(id);
            return RedirectToAction("Index");
        }

       
    }
}

Demo1-Day2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo1_Day2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo1_Day2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo1_Day2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo1_Day2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Demo1-Day2/Views/Shared/_Layout5.cshtml
@{
    ViewData["Title"] = "_Layout5";
}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/all.min.css">
    <link rel="stylesheet" href="/css/animate.css">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/aos.css">
    <link rel="stylesheet" href="/css/style.css">
    <title>Document</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light mb-0 pb-0 text-center fixed-top">
        <div class="container d-inline-flex text-center">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarSupportedContent">
                <ul class="pages-link" style="list-style: none; display: inline-flex;">
                    <li class="nav-item">
                        <a asp-controller="Department" asp-action="Index" class="nav-link">Departments</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Student" asp-action="Index" class="nav-link">Students</a>
                    </li>

                    <li class="nav-item">
                        <a asp-controller="Course" asp-action="Index" class="nav-link">Courses</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                        <a asp-controller="Account" asp-action="Logout" class="nav-link">Logout @User.Identity.Name</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Login" class="nav-link">Login</a>
                         </li>
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="Register" class="nav-link">Register</a>
                        </li>
                    }
                </ul>
            </div>

            <div class="title text-uppercase text-black font-weight-light m-1 p-1">lindsay</div>
            <div class="sub-title text-uppercase font-weight-bold text-black mt-3 pt-2 m-0 p-0"> stu<br>dio </div>
            <div class="title text-uppercase text-black font-weight-light m-1 p-1"> scholz</div>

        </div> <!-- container -->

    </nav>
    <header>
    </header>
   
    <section>
        <div class="container m-5 ps-5 " style="margin-left:9rem !important;">
            
                @* <div class="col-3"></div> *@
                @RenderBody()
                @RenderSection("ValidationScripts",false)
        </div>
    </section>
    <section>
        <div class="container m-5 p-5">
            <div class="row">
                <div class="col-6">
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt mollitia voluptate temporibus eius quo corporis maxime debitis architecto dolore sit nam, dolorem natus maiores officiis. Ducimus veniam facilis modi eius sunt, culpa rerum sint nulla aliquid aut doloremque quod, nostrum quasi repellat voluptate ratione repudiandae. Fuga, exercitationem soluta! Inventore incidunt libero magni, a nostrum, perferendis, animi esse modi hic maiores ratione cumque illum beatae quasi doloribus magnam natus repellat aut? Sunt libero maxime rem voluptate praesentium voluptates voluptatibus expedita impedit, corporis nam ipsa eaque. Ipsum voluptas, quis neque fugit dolorem inventore aliquam itaque, nesciunt, explicabo asperiores laudantium reiciendis rerum. Quam?
                    </p>
                </div>
                <div class="col-1"></div>
                <div class="col-5">
                    <img src="/images/31.jpg" class="w-100">
                </div>
            </div>
        </div>
    </section>
    <footer class="footer  p-5" data-aos="fade-up">
        <div class="container">
            <div class="row">
                <div class="col-1 text-uppercase group ">
                    <ul>
                        <li><a href="#">HOME</a></li>
                        <li><a href="#">ABOUT</a></li>
                        <li><a href="#">SERVICES</a></li>
                        <li><a href="#">WORK</a></li>
                    </ul>
                </div> <!-- c1 -->

                <div class="col-1 text-uppercase group ">
                    <ul>
                        <li><a href="#">SHOP</a></li>
                        <li><a href="#">BLOG</a></li>
                        <li><a href="#">RESOURES</a></li>
                        <li><a href="#">CONTACT</a></li>
                    </ul>
                </div> <!-- c2 -->

                <div class="col-1 text-uppercase group ">
                    <ul>
                        <li><a href="#">INSTGRAM</a></li>
                        <li><a href="#">PINTEREST</a></li>
                        <li><a href="#">FACEBOOK</a></li>
                    </ul>
                </div> <!-- c3 -->
                <div class="col-1"></div>
                <div class="col-4 text-center mt-4 pt-4">
                    <!-- هنكتب هنا الشعار  -->
                    <i class="fa fa-couch fa-8x"></i>
                    <p class="copyright ">&copy; 2017-2023 Lindsay Scholz Studio LLC.Privacy.Terms & Conditions</p>
                </div> <!-- 5cols -->

                <div class="col-4">
                    <h2 class="text-black-50 footerheader">20+ business tools for you</h2>
                    <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias assumenda voluptatem dolorem tempore quia nemo?</p>
                    <a href="#" class="text-uppercase ml-5 pl-5">get the guide <i class="fa fa-arrow-right "></i></a>
                </div>
            </div> <!-- row -->

        </div>
    </footer>

    <script src="/js/jquery-3.5.1.slim.min.js"></script>
    <script src="/js/bootstrap.bundle.min.js"></script>
    <script src="/js/wow.min.js"></script>
    <script>
        new WOW().init();
    </script>
    <script src="/js/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>